version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/build/code"
    schedule:
      interval: "daily"

    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
